-- M2MSYS.TN_MOBILE_BLVSTCK_HIST definition

CREATE TABLE "M2MSYS"."TN_MOBILE_BLVSTCK_HIST" 
   (	"FRMHS_NO" CHAR(8) NOT NULL ENABLE, 
	"LSTKSP_CL" CHAR(6) NOT NULL ENABLE, 
	"CHANGE_DT" DATE NOT NULL ENABLE, 
	"BRD_HAD_CO" NUMBER(12,0) NOT NULL ENABLE, 
	"REPRSNT_SN" NUMBER(2,0), 
	"FRST_CRTR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FRST_CREAT_DT" DATE NOT NULL ENABLE, 
	"FRST_CRTR_IP_NM" VARCHAR2(80) NOT NULL ENABLE, 
	"LAST_CHANGER_ID" VARCHAR2(20), 
	"LAST_CHANGE_DT" DATE, 
	"LAST_CHANGER_IP_NM" VARCHAR2(80), 
	"MASTER_ORG" VARCHAR2(20), 
	"MASTER_STTUS_SE" CHAR(1), 
	"MGR_CODE" CHAR(6), 
	"FRMHS_LSTKSP_CL_CODE" CHAR(6), 
	"BRD_PURPS_CODE" CHAR(10), 
	"EXAMIN_DE" DATE, 
	"REGIST_SE_CODE" CHAR(6), 
	"MOTHER_PIG_CO" NUMBER, 
	"PORKER_CO" NUMBER, 
	"MXMM_BRD_CO" NUMBER, 
	"RE_PREARNGE_DE" DATE, 
	"SEAR_SE" CHAR(1), 
	"KEEP_CODE" CHAR(6), 
	"AVG_CNT" NUMBER, 
	 CONSTRAINT "TN_MOBILE_BLVSTCK_HIST_PK" PRIMARY KEY ("FRMHS_NO", "LSTKSP_CL", "CHANGE_DT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 261095424 NEXT 104857600 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_BLVSTCK_HIST_IX_1" ON "M2MSYS"."TN_MOBILE_BLVSTCK_HIST" ("FRMHS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 152043520 NEXT 104857600 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_IDX" ;

COMMENT ON TABLE M2MSYS.TN_MOBILE_BLVSTCK_HIST IS '사육가축이력';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.FRMHS_NO IS '농가번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.LSTKSP_CL IS '축종코드';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.CHANGE_DT IS '변경일시';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.BRD_HAD_CO IS '사육두수';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.REPRSNT_SN IS '대표순번';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.FRST_CRTR_ID IS '최초생성자ID';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.FRST_CREAT_DT IS '최초생성일시';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.FRST_CRTR_IP_NM IS '최초생성자IP명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.LAST_CHANGER_ID IS '최종변경자ID';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.LAST_CHANGE_DT IS '최종변경일시';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.LAST_CHANGER_IP_NM IS '최종변경자IP명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.MASTER_ORG IS '관리기관';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.MASTER_STTUS_SE IS '농장운영상태';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.MGR_CODE IS '축종운영상태(방역본부)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.FRMHS_LSTKSP_CL_CODE IS '축종코드구분';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.BRD_PURPS_CODE IS '사육목적코드';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.EXAMIN_DE IS '조사일자';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.REGIST_SE_CODE IS '등록상태코드';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.MOTHER_PIG_CO IS '모돈두수';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.PORKER_CO IS '돼지두수';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.MXMM_BRD_CO IS '최대사육두수';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.RE_PREARNGE_DE IS '재예정일자';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.SEAR_SE IS '조회구분(Y/N)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.KEEP_CODE IS '유지코드';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_BLVSTCK_HIST.AVG_CNT IS '평균사육두수';