-- M2MSYS.TN_MOBILE_FRMHS_INFO definition

CREATE TABLE "M2MSYS"."TN_MOBILE_FRMHS_INFO" 
   (	"FRMHS_NO" CHAR(8) NOT NULL ENABLE, 
	"FCLTY_SN" NUMBER(4,0) NOT NULL ENABLE, 
	"FRMHS_NM" VARCHAR2(100), 
	"LTKRSR_NM" VARCHAR2(100), 
	"INDUTY_CL" CHAR(3), 
	"BSNS_STTUS_SE" CHAR(1), 
	"CTPRVN_CL" VARCHAR2(2), 
	"FRMHS_TELNO" VARCHAR2(50), 
	"FRMHS_MBTELNO" VARCHAR2(50), 
	"FRMHS_ADRES" VARCHAR2(100), 
	"FRMHS_DETAIL_ADRES" VARCHAR2(200), 
	"MNTN_LC" CHAR(1), 
	"BON_LC" CHAR(4), 
	"BU_LC" CHAR(4), 
	"LEGALDONG_CL" CHAR(10), 
	"BLDNG_MNG_NO" CHAR(25), 
	"ROAD_NM_CL" CHAR(12), 
	"ROAD_NM" VARCHAR2(150), 
	"UNDR_SE" CHAR(1), 
	"BLDNG_BON" CHAR(5), 
	"BLDNG_BU" CHAR(5), 
	"BLDNG_NM" VARCHAR2(60), 
	"DETAIL_BLDNG_NM" VARCHAR2(100), 
	"FRST_CRTR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FRST_CREAT_DT" DATE NOT NULL ENABLE, 
	"FRST_CRTR_IP_NM" VARCHAR2(80) NOT NULL ENABLE, 
	"LAST_CHANGER_ID" VARCHAR2(20), 
	"LAST_CHANGE_DT" DATE, 
	"LAST_CHANGER_IP_NM" VARCHAR2(80), 
	"DELETE_AT" CHAR(1) DEFAULT 'N', 
	"DELETER_ID" VARCHAR2(20), 
	"DELETE_DT" DATE, 
	"DELETER_IP_NM" VARCHAR2(80), 
	"FRMHS_MAPNG_NO" CHAR(8), 
	"SURVEY_TY" CHAR(2), 
	"CORD_YN" CHAR(1) DEFAULT 'N', 
	"UPDAT_ETC" VARCHAR2(4000), 
	"UPDAT_ID" VARCHAR2(20), 
	"UPDAT_DT" DATE, 
	"UPDAT_IP_NM" VARCHAR2(80), 
	"TEL_CORD_TY" CHAR(2), 
	"TEL_SURVEY_TY1" CHAR(2), 
	"TEL_SURVEY_TY2" CHAR(2), 
	"MAP_KEY" CHAR(8), 
	"FDB_SE" CHAR(1), 
	"FDB_FRMHS_SN" NUMBER, 
	"INDUTY_STATS_CL" CHAR(3), 
	 CONSTRAINT "TN_MOBILE_FRMHS_INFO_PK" PRIMARY KEY ("FRMHS_NO", "FCLTY_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 10485760 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 104857600 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX08" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("DELETE_AT", "INDUTY_CL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX09" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("FRMHS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IX01" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("DELETE_AT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 52428800 NEXT 10485760 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_IDX" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX03" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("INDUTY_CL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX04" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("LEGALDONG_CL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_IDX" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX02" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("LTKRSR_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX05" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("FRMHS_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX06" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("FDB_FRMHS_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 MAXSIZE UNLIMITED
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

CREATE INDEX "M2MSYS"."TN_MOBILE_FRMHS_INFO_IDX07" ON "M2MSYS"."TN_MOBILE_FRMHS_INFO" ("MAP_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "M2M_DATA" ;

COMMENT ON TABLE M2MSYS.TN_MOBILE_FRMHS_INFO IS '모바일농장정보';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_NO IS '농가번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FCLTY_SN IS '시설순번';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_NM IS '농장명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.LTKRSR_NM IS '축주명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.INDUTY_CL IS '업종분류';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BSNS_STTUS_SE IS '사업상태구분';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.CTPRVN_CL IS '시도분류';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_TELNO IS '농장전화번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_MBTELNO IS '농장휴대전화번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_ADRES IS '농장주소';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_DETAIL_ADRES IS '농장상세주소';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.MNTN_LC IS '산위치';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BON_LC IS '본위치';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BU_LC IS '부위치';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.LEGALDONG_CL IS '법정동분류';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BLDNG_MNG_NO IS '건물관리번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.ROAD_NM_CL IS '도로명분류';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.ROAD_NM IS '도로명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.UNDR_SE IS '지하구분';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BLDNG_BON IS '건물본번';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BLDNG_BU IS '건물부번';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.BLDNG_NM IS '건물명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.DETAIL_BLDNG_NM IS '상세건물명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRST_CRTR_ID IS '최초생성자ID';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRST_CREAT_DT IS '최초생성일시';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRST_CRTR_IP_NM IS '최초생성자IP명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.LAST_CHANGER_ID IS '최종변경자ID';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.LAST_CHANGE_DT IS '최종변경일시';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.LAST_CHANGER_IP_NM IS '최종변경자IP명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.DELETE_AT IS '삭제여부';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.DELETER_ID IS '삭제자ID';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.DELETE_DT IS '삭제일시';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.DELETER_IP_NM IS '삭제자IP명';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FRMHS_MAPNG_NO IS '매핑농장번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.SURVEY_TY IS '조사방법';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.CORD_YN IS '좌표등록여부(A782)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.UPDAT_ETC IS '비고(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.UPDAT_ID IS '변경자(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.UPDAT_DT IS '변경일시(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.UPDAT_IP_NM IS '변경자IP명(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.TEL_CORD_TY IS '반경조사-A785(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.TEL_SURVEY_TY1 IS '전화조사-A783(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.TEL_SURVEY_TY2 IS '전화조사-A784(GPS운영센터확인)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.MAP_KEY IS 'MAP키';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FDB_SE IS '통합DB확인여부(Y:통합DB검증완료,C:통합DB신규)';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.FDB_FRMHS_SN IS '통합DB농장식별번호';
COMMENT ON COLUMN M2MSYS.TN_MOBILE_FRMHS_INFO.INDUTY_STATS_CL IS '업종분류-A763(통계용)';