-- LSFARM.EAI_TN_FARM_INFO definition

CREATE TABLE "LSFARM"."EAI_TN_FARM_INFO" 
   (	"FARM_NO" NUMBER NOT NULL ENABLE, 
	"FARM_NM" VARCHAR2(100), 
	"BRD_OWNER_NM" VARCHAR2(100), 
	"IHIDNUM" VARCHAR2(13), 
	"DO_INSTT_CODE" CHAR(7), 
	"AGNC_CODE" CHAR(7), 
	"AREA_CODE" CHAR(7), 
	"CTPRVN_CODE" CHAR(7), 
	"SIGUNGU_CODE" CHAR(7), 
	"OWNHOM_OLD_LEGALDONG_CODE" CHAR(10), 
	"OWNHOM_OLD_ZIP_NO" VARCHAR2(6), 
	"OWNHOM_OLD_BASS_ADRES" VARCHAR2(200), 
	"OWNHOM_OLD_DETAIL_ADRES" VARCHAR2(200), 
	"OWNHOM_BULD_MANAGE_NO" CHAR(25), 
	"OWNHOM_LEGALDONG_CODE" CHAR(10), 
	"OWNHOM_ZIP_NO" VARCHAR2(6), 
	"OWNHOM_DETAIL_ADRES" VARCHAR2(200), 
	"FRMHS_OLD_LEGALDONG_CODE" CHAR(10), 
	"FRMHS_OLD_ZIP_NO" VARCHAR2(6), 
	"FRMHS_OLD_BASS_ADRES" VARCHAR2(200), 
	"FRMHS_OLD_DETAIL_ADRES" VARCHAR2(200), 
	"FRMHS_BULD_MANAGE_NO" CHAR(25), 
	"FRMHS_LEGALDONG_CODE" CHAR(10), 
	"FRMHS_ZIP_NO" VARCHAR2(6), 
	"FRMHS_DETAIL_ADRES" VARCHAR2(200), 
	"LA_DEGREE" CHAR(2), 
	"LA_MIN" CHAR(2), 
	"LA_SECND1" CHAR(2), 
	"LA_SECND2" CHAR(2), 
	"LO_DEGREE" CHAR(3), 
	"LO_MIN" CHAR(2), 
	"LO_SECND1" CHAR(2), 
	"LO_SECND2" CHAR(2), 
	"LSIND_REGIST_NO" VARCHAR2(30), 
	"PIG_FARM_NO" VARCHAR2(30), 
	"POSESN_MTHD_CODE" CHAR(6), 
	"FRMHS_STTUS_CODE" CHAR(6), 
	"MNGMT_MTHD_CODE" CHAR(6), 
	"REPRSNT_FARM_NO" NUMBER, 
	"REPRSNT_BRD_YN" CHAR(1), 
	"PR_RECPT_YN" CHAR(1), 
	"PR_RECPT_CODE" CHAR(6), 
	"PREDICTN_PROGRS_SE" CHAR(6), 
	"DISS_MANAGE_GRAD_CODE" CHAR(6), 
	"FARM_INFO_SRC" CHAR(6), 
	"CNTC_ID" VARCHAR2(30), 
	"RE_PREARNGE_DE" DATE, 
	"LAST_PREDICTN_TALK_DT" DATE, 
	"DSNFC_PARTCLR_CN" VARCHAR2(2000), 
	"PREDC_PARTCLR_CN" VARCHAR2(2000), 
	"ETC_CN" VARCHAR2(2000), 
	"PREDICTN_PARTCLR_CN" VARCHAR2(2000), 
	"WRLESS_INTNET_YN" CHAR(1), 
	"FARM_SE" CHAR(1) DEFAULT '0', 
	"ALBS_FARMS_TMP_SEQ" NUMBER, 
	"USE_SE" CHAR(1) DEFAULT 'Y', 
	"REGIST_DE" DATE, 
	"REGISTER_SN" NUMBER, 
	"UPDT_DE" DATE, 
	"UPDUSR_SN" NUMBER, 
	"DSNFC_SN" NUMBER, 
	"FIN_NO" CHAR(6), 
	"OWNHOM_ROAD_CODE" CHAR(12), 
	"FRMHS_ROAD_CODE" CHAR(12), 
	"OWNHOM_EMD_SN" VARCHAR2(2), 
	"FRMHS_EMD_SN" VARCHAR2(2), 
	"OWNHOM_SEQ_SN" NUMBER, 
	"FRMHS_SEQ_SN" NUMBER, 
	"D_LA_DEGREE" CHAR(2), 
	"D_LA_MIN" CHAR(2), 
	"D_LA_SECND1" CHAR(2), 
	"D_LA_SECND2" CHAR(2), 
	"D_LO_DEGREE" CHAR(3), 
	"D_LO_MIN" CHAR(2), 
	"D_LO_SECND1" CHAR(2), 
	"D_LO_SECND2" CHAR(2), 
	"SD_LA_DEGREE" CHAR(2), 
	"SD_LA_MIN" CHAR(2), 
	"SD_LA_SECND1" CHAR(2), 
	"SD_LA_SECND2" CHAR(2), 
	"SD_LO_DEGREE" CHAR(3), 
	"SD_LO_MIN" CHAR(2), 
	"SD_LO_SECND1" CHAR(2), 
	"SD_LO_SECND2" CHAR(2), 
	"BD_LA_DEGREE" CHAR(2), 
	"BD_LA_MIN" CHAR(2), 
	"BD_LA_SECND1" CHAR(2), 
	"BD_LA_SECND2" CHAR(2), 
	"BD_LO_DEGREE" CHAR(3), 
	"BD_LO_MIN" CHAR(2), 
	"BD_LO_SECND1" CHAR(2), 
	"BD_LO_SECND2" CHAR(2), 
	"MGR_FARM_CODE" CHAR(6), 
	"OWNHOM_DAUM_ROAD_ADDR" VARCHAR2(200), 
	"FRMHS_DAUM_ROAD_ADDR" VARCHAR2(200), 
	"OWNER_BIRTH" DATE, 
	"SF_TEAM_CODE" CHAR(7), 
	"MG_REG_NO" VARCHAR2(30), 
	"RGT_MBD_REG_NO" VARCHAR2(13), 
	"RGT_MBD_SNO" VARCHAR2(3), 
	"PNU" VARCHAR2(19), 
	"DSNFC_MGR_CODE" CHAR(6), 
	"TLPRE_MGR_CODE" CHAR(6), 
	"INDVDINFO_AGRE_YN" CHAR(1), 
	"INDVDINFO_AGRE_DE" DATE, 
	"REGSTBASIS_SE_CODE" CHAR(6), 
	 CONSTRAINT "PK_EAI_TN_FARM_INFO" PRIMARY KEY ("FARM_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_06" ;

CREATE INDEX "LSFARM"."IX_TN_FARM_INFO_02" ON "LSFARM"."EAI_TN_FARM_INFO" (SUBSTR("FRMHS_OLD_LEGALDONG_CODE",1,2), "FARM_NO" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03" ;

CREATE INDEX "LSFARM"."IX_TN_FARM_INFO_03" ON "LSFARM"."EAI_TN_FARM_INFO" (SUBSTR("FRMHS_OLD_LEGALDONG_CODE",1,5), "FARM_NO" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03" ;

CREATE INDEX "LSFARM"."IX_TN_FARM_INFO_04" ON "LSFARM"."EAI_TN_FARM_INFO" (SUBSTR("FRMHS_OLD_LEGALDONG_CODE",1,8), "FARM_NO" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03" ;

CREATE INDEX "LSFARM"."IX_TN_FARM_INFO_05" ON "LSFARM"."EAI_TN_FARM_INFO" ("FRMHS_ROAD_CODE", "FARM_NO" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03" ;

CREATE INDEX "LSFARM"."IX_TN_FARM_INFO_06" ON "LSFARM"."EAI_TN_FARM_INFO" ("REPRSNT_FARM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03" ;

GRANT DELETE ON "LSFARM"."EAI_TN_FARM_INFO" TO "LSFARM_EAI";
 
  GRANT INSERT ON "LSFARM"."EAI_TN_FARM_INFO" TO "LSFARM_EAI";
 
  GRANT SELECT ON "LSFARM"."EAI_TN_FARM_INFO" TO "LSFARM_EAI";
 
  GRANT UPDATE ON "LSFARM"."EAI_TN_FARM_INFO" TO "LSFARM_EAI";

COMMENT ON TABLE LSFARM.EAI_TN_FARM_INFO IS '농장정보';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FARM_NO IS '농장번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FARM_NM IS '농장명';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BRD_OWNER_NM IS '축주명';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.IHIDNUM IS '주민등록번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.DO_INSTT_CODE IS '도_기관코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.AGNC_CODE IS '출장소코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.AREA_CODE IS '지역코드(방역사관리)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.CTPRVN_CODE IS '시도코드(농장)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SIGUNGU_CODE IS '시군구코드(농장)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_OLD_LEGALDONG_CODE IS '자택_구법정동코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_OLD_ZIP_NO IS '자택_구우편번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_OLD_BASS_ADRES IS '자택_구기본주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_OLD_DETAIL_ADRES IS '자택_구상세주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_BULD_MANAGE_NO IS '자택_건물관리번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_LEGALDONG_CODE IS '자택_법정동코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_ZIP_NO IS '자택_우편번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_DETAIL_ADRES IS '자택_상세주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_OLD_LEGALDONG_CODE IS '농장_구법정동코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_OLD_ZIP_NO IS '농장_구우편번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_OLD_BASS_ADRES IS '농장_구기본주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_OLD_DETAIL_ADRES IS '농장_구상세주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_BULD_MANAGE_NO IS '농장_건물관리번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_LEGALDONG_CODE IS '농장_법정동코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_ZIP_NO IS '농장_우편번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_DETAIL_ADRES IS '농장_상세주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LA_DEGREE IS '위도_도';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LA_MIN IS '위도_분';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LA_SECND1 IS '위도_초1';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LA_SECND2 IS '위도_초2';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LO_DEGREE IS '경도_도';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LO_MIN IS '경도_분';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LO_SECND1 IS '경도_초1';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LO_SECND2 IS '경도_초2';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LSIND_REGIST_NO IS '축산업등록번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PIG_FARM_NO IS '돼지농장번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.POSESN_MTHD_CODE IS '소유방식코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_STTUS_CODE IS '농가운영상태코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.MNGMT_MTHD_CODE IS '경영방식코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.REPRSNT_FARM_NO IS '대표농장번호(소유주번호)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.REPRSNT_BRD_YN IS '대표축주여부';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PR_RECPT_YN IS '홍보물수령여부';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PR_RECPT_CODE IS '홍보물수령처코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PREDICTN_PROGRS_SE IS '예찰진행구분코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.DISS_MANAGE_GRAD_CODE IS '질병관리등급분류코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FARM_INFO_SRC IS '농장정보소스';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.CNTC_ID IS '연계ID';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.RE_PREARNGE_DE IS '재입식예정일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.LAST_PREDICTN_TALK_DT IS '최종예찰일시';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.DSNFC_PARTCLR_CN IS '방역사특이사항';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PREDC_PARTCLR_CN IS '홍보교육특이사항';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.ETC_CN IS '기타내용(기타특이사항)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PREDICTN_PARTCLR_CN IS '전화예찰특이사항';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.WRLESS_INTNET_YN IS '무선인터넷가능여부(가능:Y)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FARM_SE IS '농가구분(1:선정농가, 0:불특정농가)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.ALBS_FARMS_TMP_SEQ IS '오토젠LBS농가임시일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.USE_SE IS '사용구분(사용:Y)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.REGIST_DE IS '등록일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.REGISTER_SN IS '등록자_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.UPDT_DE IS '수정일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.UPDUSR_SN IS '수정자_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.DSNFC_SN IS '방역사일련번호(관리방역사)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FIN_NO IS '고유식별번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_ROAD_CODE IS '자택_도로명코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_ROAD_CODE IS '농장_도로명코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_EMD_SN IS '자택_읍면동일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_EMD_SN IS '농장_읍면동일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_SEQ_SN IS '자택_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_SEQ_SN IS '농장_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LA_DEGREE IS '출입구_위도_도        ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LA_MIN IS '출입구_위도_분        ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LA_SECND1 IS '출입구_위도_초1       ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LA_SECND2 IS '출입구_위도_초2       ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LO_DEGREE IS '출입구_경도_도        ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LO_MIN IS '출입구_경도_분        ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LO_SECND1 IS '출입구_경도_초1       ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.D_LO_SECND2 IS '출입구_경도_초2       ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LA_DEGREE IS '부출입구_위도_도      ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LA_MIN IS '부출입구_위도_분      ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LA_SECND1 IS '부출입구_위도_초1     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LA_SECND2 IS '부출입구_위도_초2     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LO_DEGREE IS '부출입구_경도_도      ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LO_MIN IS '부출입구_경도_분      ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LO_SECND1 IS '부출입구_경도_초1     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SD_LO_SECND2 IS '부출입구_경도_초2     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LA_DEGREE IS '부출입구2_위도_도     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LA_MIN IS '부출입구2_위도_분     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LA_SECND1 IS '부출입구2_위도_초1    ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LA_SECND2 IS '부출입구2_위도_초2    ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LO_DEGREE IS '부출입구2_경도_도     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LO_MIN IS '부출입구2_경도_분     ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LO_SECND1 IS '부출입구2_경도_초1    ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.BD_LO_SECND2 IS '부출입구2_경도_초2    ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.MGR_FARM_CODE IS '관리농장              ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNHOM_DAUM_ROAD_ADDR IS '자택_다음맵_도로명주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.FRMHS_DAUM_ROAD_ADDR IS '농장_다음맵_도로명주소';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.OWNER_BIRTH IS '축주_생년월일         ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.SF_TEAM_CODE IS '자치단체코드          ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.MG_REG_NO IS '권리등록번호          ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.RGT_MBD_REG_NO IS '권리주체등록번호      ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.RGT_MBD_SNO IS '권리주체일련번호      ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.PNU IS '농장PNU코드           ';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.DSNFC_MGR_CODE IS '방역관리구분코드(414)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.TLPRE_MGR_CODE IS '방역관리구분코드(전화예찰관리구분코드(415))';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.INDVDINFO_AGRE_YN IS '개인정보동의여부';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.INDVDINFO_AGRE_DE IS '개인정보동의일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_INFO.REGSTBASIS_SE_CODE IS '신규등재근거구분코드(416)';