-- LSFARM.EAI_TN_FARM_SCALE_DETAIL definition

CREATE TABLE "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" 
   (	"FARM_NO" NUMBER NOT NULL ENABLE, 
	"UPPER_PRDLST_CODE" CHAR(6) NOT NULL ENABLE, 
	"SPCIES_CODE" CHAR(6) NOT NULL ENABLE, 
	"SEQ_SN" NUMBER NOT NULL ENABLE, 
	"DETAIL_SPCIES_CODE" CHAR(6), 
	"BRD_CO" NUMBER, 
	"SORT_ORDR" NUMBER, 
	"RM" VARCHAR2(2000), 
	"REGIST_DE" DATE, 
	"REGISTER_SN" NUMBER, 
	"UPDT_DE" DATE, 
	"UPDUSR_SN" NUMBER, 
	"CHCKN_GROUP" NUMBER, 
	"AVG_CNT" NUMBER, 
	"MGR_CODE" CHAR(6), 
	"KEEP_CODE" CHAR(6), 
	"CHARGE_CODE" CHAR(1), 
	"BRD_PURPS_CODE" CHAR(10), 
	"EXAMIN_DE" DATE, 
	"REGIST_SE_CODE" CHAR(6), 
	"MOTHER_PIG_CO" NUMBER, 
	"PORKER_CO" NUMBER, 
	"MXMM_BRD_CO" NUMBER, 
	"RE_PREARNGE_DE" DATE, 
	"SEAR_SE" CHAR(1), 
	 CONSTRAINT "PK_EAI_TN_FARM_SCALE_DETAIL" PRIMARY KEY ("FARM_NO", "UPPER_PRDLST_CODE", "SPCIES_CODE", "SEQ_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_07" ;

CREATE INDEX "LSFARM"."IX_EAI_TN_FARM_SCALE_DETAIL_02" ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" ("MGR_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_09" ;

CREATE INDEX "LSFARM"."IX_EAI_TN_FARM_SCALE_DETAIL_03" ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" ("SEAR_SE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_09" ;

CREATE INDEX "LSFARM"."IX_EAI_TN_FARM_SCALE_DETAIL_04" ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" ("FARM_NO", "UPPER_PRDLST_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_09" ;

CREATE INDEX "LSFARM"."IX_EAI_TN_FARM_SCALE_DETAIL_05" ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" ("SPCIES_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_09" ;

CREATE INDEX "LSFARM"."IX_EAI_TN_FARM_SCALE_DETAIL_06" ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" ("FARM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_09" ;

GRANT DELETE ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" TO "LSFARM_EAI";
 
  GRANT INSERT ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" TO "LSFARM_EAI";
 
  GRANT SELECT ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" TO "LSFARM_EAI";
 
  GRANT UPDATE ON "LSFARM"."EAI_TN_FARM_SCALE_DETAIL" TO "LSFARM_EAI";

COMMENT ON TABLE LSFARM.EAI_TN_FARM_SCALE_DETAIL IS '농장정보_사육규모현황상세';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.FARM_NO IS '농장번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.UPPER_PRDLST_CODE IS '축종코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.SPCIES_CODE IS '품종코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.SEQ_SN IS '일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.DETAIL_SPCIES_CODE IS '상세품종코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.BRD_CO IS '사육두수';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.SORT_ORDR IS '정렬순서';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.RM IS '비고';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.REGIST_DE IS '등록일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.REGISTER_SN IS '등록자_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.UPDT_DE IS '수정일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.UPDUSR_SN IS '수정자_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.CHCKN_GROUP IS '계군(주령)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.AVG_CNT IS '현행화_상시두수';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.MGR_CODE IS '현행화_운영상태';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.KEEP_CODE IS '현행화_사육방식';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.CHARGE_CODE IS '현행화_위탁유무';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.BRD_PURPS_CODE IS '사육목적코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.EXAMIN_DE IS '조사일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.REGIST_SE_CODE IS '등록구분코드(409)_조사구분코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.MOTHER_PIG_CO IS '모돈수';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.PORKER_CO IS '비육돈수';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.MXMM_BRD_CO IS '최대사육두수';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.RE_PREARNGE_DE IS '재입식예정일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE_DETAIL.SEAR_SE IS '조회구분(Y/N)';