-- LSFARM.EAI_TN_FARM_SCALE definition

CREATE TABLE "LSFARM"."EAI_TN_FARM_SCALE" 
   (	"FARM_NO" NUMBER NOT NULL ENABLE, 
	"UPPER_PRDLST_CODE" CHAR(6) NOT NULL ENABLE, 
	"FARM_REGIST_NO" VARCHAR2(20), 
	"BRD_CO" NUMBER, 
	"SORT_ORDR" NUMBER, 
	"RM" VARCHAR2(2000), 
	"EXAMIN_MTH_CODE" CHAR(6), 
	"REGIST_DE" DATE, 
	"REGISTER_SN" NUMBER, 
	"UPDT_DE" DATE, 
	"UPDUSR_SN" NUMBER, 
	"MENT_CODE" CHAR(6), 
	"EXAMIN_DE" DATE, 
	"REGIST_SE_CODE" CHAR(6), 
	"MGR_CODE" CHAR(6), 
	"UPRDLST_DSNFC_MGR_CODE" CHAR(6), 
	 CONSTRAINT "PK_EAI_TN_FARM_SCALE" PRIMARY KEY ("FARM_NO", "UPPER_PRDLST_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_03"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_07" ;

CREATE INDEX "LSFARM"."IX_EAI_TN_FARM_SCALE_02" ON "LSFARM"."EAI_TN_FARM_SCALE" ("FARM_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS005_09" ;

GRANT DELETE ON "LSFARM"."EAI_TN_FARM_SCALE" TO "LSFARM_EAI";
 
  GRANT INSERT ON "LSFARM"."EAI_TN_FARM_SCALE" TO "LSFARM_EAI";
 
  GRANT SELECT ON "LSFARM"."EAI_TN_FARM_SCALE" TO "LSFARM_EAI";
 
  GRANT UPDATE ON "LSFARM"."EAI_TN_FARM_SCALE" TO "LSFARM_EAI";

COMMENT ON TABLE LSFARM.EAI_TN_FARM_SCALE IS '농장정보_사육규모현황';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.FARM_NO IS '농장번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.UPPER_PRDLST_CODE IS '축종코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.FARM_REGIST_NO IS '농장등록번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.BRD_CO IS '사육두수';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.SORT_ORDR IS '정렬순서';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.RM IS '비고';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.EXAMIN_MTH_CODE IS '조사방법코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.REGIST_DE IS '등록일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.REGISTER_SN IS '등록자_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.UPDT_DE IS '수정일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.UPDUSR_SN IS '수정자_일련번호';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.MENT_CODE IS '경영상태';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.EXAMIN_DE IS '조사일자';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.REGIST_SE_CODE IS '등록구분코드(409)_조사구분코드';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.MGR_CODE IS '축종_운영상태(104)';
COMMENT ON COLUMN LSFARM.EAI_TN_FARM_SCALE.UPRDLST_DSNFC_MGR_CODE IS '축종방역관리코드(418)';