-- LSFARM.TN_FRMHS definition

CREATE TABLE "LSFARM"."TN_FRMHS" 
   (	"FRMHS_SN" NUMBER(13,0) NOT NULL ENABLE, 
	"FRMHS_IDNTFC_NO" CHAR(6), 
	"LSIND_REGIST_NO" VARCHAR2(50), 
	"OWNER_NM" VARCHAR2(100), 
	"IHIDNUM_SUMRY" VARCHAR2(7), 
	"FRMHS_NM" VARCHAR2(100), 
	"FRMHS_TELNO" VARCHAR2(20), 
	"OWNER_TELNO" VARCHAR2(20), 
	"MBTLNUM" VARCHAR2(20), 
	"ZIP" CHAR(6), 
	"LEGALDONG_CODE" CHAR(10), 
	"LEGALDONG_DETAIL_ADRES" VARCHAR2(200), 
	"RN" VARCHAR2(100), 
	"RN_DETAIL_ADRES" VARCHAR2(200), 
	"FRMHS_AR" NUMBER, 
	"BSNS_STTUS_CODE" CHAR(1) NOT NULL ENABLE, 
	"POSESN_STLE_CODE" CHAR(1), 
	"USE_AT" CHAR(1) DEFAULT 'Y', 
	"FRST_CRTR_ID" VARCHAR2(20), 
	"FRST_CREAT_DT" DATE, 
	"FRST_CRTR_IP_NM" VARCHAR2(80), 
	"LAST_CHANGER_ID" VARCHAR2(20), 
	"LAST_CHANGE_DT" DATE, 
	"LAST_CHANGER_IP_NM" VARCHAR2(80), 
	"NEW_FRMHS_AT" CHAR(1) DEFAULT 'N', 
	"LNM_NRMLT_AT" CHAR(1), 
	"CTTPC_NRMLT_AT" CHAR(1), 
	"BRD_NRMLT_AT" CHAR(1), 
	"MG_REG_NO" VARCHAR2(30), 
	"DSNFC_MGR_CODE" CHAR(6), 
	"TLPRE_MGR_CODE" CHAR(6), 
	"INDVDINFO_AGRE_YN" CHAR(1), 
	"INDVDINFO_AGRE_DE" DATE, 
	"REGSTBASIS_SE_CODE" CHAR(6), 
	 CONSTRAINT "PK_FARMHS" PRIMARY KEY ("FRMHS_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_05"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS001_03" ;

GRANT DELETE ON "LSFARM"."TN_FRMHS" TO "LSFARM_EAI";
 
  GRANT INSERT ON "LSFARM"."TN_FRMHS" TO "LSFARM_EAI";
 
  GRANT SELECT ON "LSFARM"."TN_FRMHS" TO "LSFARM_EAI";
 
  GRANT UPDATE ON "LSFARM"."TN_FRMHS" TO "LSFARM_EAI";

COMMENT ON TABLE LSFARM.TN_FRMHS IS '농장';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRMHS_SN IS '농장_일련번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRMHS_IDNTFC_NO IS '농장_식별_번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LSIND_REGIST_NO IS '축산업_등록_번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.OWNER_NM IS '소유주_명';
COMMENT ON COLUMN LSFARM.TN_FRMHS.IHIDNUM_SUMRY IS '주민등록번호_요약';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRMHS_NM IS '농장_명';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRMHS_TELNO IS '농장_전화번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.OWNER_TELNO IS '소유주_전화번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.MBTLNUM IS '휴대폰번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.ZIP IS '우편번호';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LEGALDONG_CODE IS '법정동_코드';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LEGALDONG_DETAIL_ADRES IS '법정동_상세_주소';
COMMENT ON COLUMN LSFARM.TN_FRMHS.RN IS '도로명';
COMMENT ON COLUMN LSFARM.TN_FRMHS.RN_DETAIL_ADRES IS '도로명_상세_주소';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRMHS_AR IS '농장_면적';
COMMENT ON COLUMN LSFARM.TN_FRMHS.BSNS_STTUS_CODE IS '운영_상태_코드';
COMMENT ON COLUMN LSFARM.TN_FRMHS.POSESN_STLE_CODE IS '소유_형태_코드';
COMMENT ON COLUMN LSFARM.TN_FRMHS.USE_AT IS '사용_여부';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRST_CRTR_ID IS '최초_생성자_ID';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRST_CREAT_DT IS '최초_생성_일시';
COMMENT ON COLUMN LSFARM.TN_FRMHS.FRST_CRTR_IP_NM IS '최초_생성자_IP_명';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LAST_CHANGER_ID IS '최종_변경자_ID';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LAST_CHANGE_DT IS '최종_변경_일시';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LAST_CHANGER_IP_NM IS '최종_변경자_IP_명';
COMMENT ON COLUMN LSFARM.TN_FRMHS.NEW_FRMHS_AT IS '신규_농장_여부';
COMMENT ON COLUMN LSFARM.TN_FRMHS.LNM_NRMLT_AT IS '지번_정상_여부';
COMMENT ON COLUMN LSFARM.TN_FRMHS.CTTPC_NRMLT_AT IS '연락처_정상_여부';
COMMENT ON COLUMN LSFARM.TN_FRMHS.BRD_NRMLT_AT IS '사육정보_정상_여부';
COMMENT ON COLUMN LSFARM.TN_FRMHS.DSNFC_MGR_CODE IS '방역관리구분코드(414)';
COMMENT ON COLUMN LSFARM.TN_FRMHS.TLPRE_MGR_CODE IS '전화예찰관리구분코드(415)';
COMMENT ON COLUMN LSFARM.TN_FRMHS.INDVDINFO_AGRE_YN IS '개인정보동의여부';
COMMENT ON COLUMN LSFARM.TN_FRMHS.INDVDINFO_AGRE_DE IS '개인정보동의일자';
COMMENT ON COLUMN LSFARM.TN_FRMHS.REGSTBASIS_SE_CODE IS '신규등재근거구분코드(416)';