-- LSFARM.TN_FARMHS_NO_MAPNG definition

CREATE TABLE "LSFARM"."TN_FARMHS_NO_MAPNG" 
   (	"FRMHS_SN" NUMBER(13,0) NOT NULL ENABLE, 
	"INSTT_SE_CODE" CHAR(2) NOT NULL ENABLE, 
	"MAPNG_SN" NUMBER(13,0) NOT NULL ENABLE, 
	"CNTC_FRMHS_NO" VARCHAR2(50) NOT NULL ENABLE, 
	"USE_AT" CHAR(1) DEFAULT 'Y', 
	"FRST_CRTR_ID" VARCHAR2(20), 
	"FRST_CREAT_DT" DATE, 
	"FRST_CRTR_IP_NM" VARCHAR2(80), 
	"LAST_CHANGER_ID" VARCHAR2(20), 
	"LAST_CHANGE_DT" DATE, 
	"LAST_CHANGER_IP_NM" VARCHAR2(80), 
	 CONSTRAINT "PK_FRMHS_NO_MAPNG" PRIMARY KEY ("FRMHS_SN", "INSTT_SE_CODE", "MAPNG_SN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_05"  ENABLE, 
	 CONSTRAINT "FK_FRMHS_NO_MAPNG_01" FOREIGN KEY ("FRMHS_SN")
	  REFERENCES "LSFARM"."TN_FRMHS" ("FRMHS_SN") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "TB_TS001_03" ;

CREATE INDEX "LSFARM"."IX_FRMHS_NO_MAPNG_02" ON "LSFARM"."TN_FARMHS_NO_MAPNG" ("INSTT_SE_CODE", "CNTC_FRMHS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "IX_TS001_05" ;

GRANT DELETE ON "LSFARM"."TN_FARMHS_NO_MAPNG" TO "LSFARM_EAI";
 
  GRANT INSERT ON "LSFARM"."TN_FARMHS_NO_MAPNG" TO "LSFARM_EAI";
 
  GRANT SELECT ON "LSFARM"."TN_FARMHS_NO_MAPNG" TO "LSFARM_EAI";
 
  GRANT UPDATE ON "LSFARM"."TN_FARMHS_NO_MAPNG" TO "LSFARM_EAI";

COMMENT ON TABLE LSFARM.TN_FARMHS_NO_MAPNG IS '농장_번호_매핑';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.FRMHS_SN IS '농장_일련번호';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.INSTT_SE_CODE IS '기관_분류_코드';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.MAPNG_SN IS '매핑_일련번호';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.CNTC_FRMHS_NO IS '연계_농장_번호';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.USE_AT IS '사용_여부';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.FRST_CRTR_ID IS '최초_생성자_ID';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.FRST_CREAT_DT IS '최초_생성_일시';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.FRST_CRTR_IP_NM IS '최초_생성자_IP_명';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.LAST_CHANGER_ID IS '최종_변경자_ID';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.LAST_CHANGE_DT IS '최종_변경_일시';
COMMENT ON COLUMN LSFARM.TN_FARMHS_NO_MAPNG.LAST_CHANGER_IP_NM IS '최종_변경자_IP_명';