package kr.go.kahis.batchmonitor.persistence.enumeration;

public enum ErrorType {

  LIVESTOCK_ANOMALY,
  PREDICTION_ANOMALY,
  FARM_COUNT_ANOMALY,
  PNU_ANOMALY,
  FARM_COORDINATE_MISSING,
  DATA_NOT_FOUND,
  TRAININGSET_COUNT_MISMATCH,
  CALC_ENV_ANOMALY,
  UNKNOWN;
}
