-- DPL.TN_BLVSTCK definition

CREATE TABLE "DPL"."TN_BLVSTCK" 
   (	"FRMHS_NO" CHAR(8) NOT NULL ENABLE, 
	"LSTKSP_CL" CHAR(6) NOT NULL ENABLE, 
	"BRD_HAD_CO" NUMBER(12,0) NOT NULL ENABLE, 
	"REPRSNT_SN" NUMBER(2,0), 
	"FRST_CRTR_ID" VARCHAR2(20) NOT NULL ENABLE, 
	"FRST_CREAT_DT" DATE NOT NULL ENABLE, 
	"FRST_CRTR_IP_NM" VARCHAR2(80) NOT NULL ENABLE, 
	"LAST_CHANGER_ID" VARCHAR2(20), 
	"LAST_CHANGE_DT" DATE, 
	"LAST_CHANGER_IP_NM" VARCHAR2(80), 
	"MASTER_ORG" VARCHAR2(20), 
	"MASTER_STTUS_SE" CHAR(1), 
	"MASTER_ORG_TEMP" VARCHAR2(20), 
	"MASTER_ORG_TEMP2" VARCHAR2(20), 
	"MASTER_ORG_ORI" VARCHAR2(20), 
	"MGR_CODE" CHAR(6), 
	"FRMHS_LSTKSP_CL_CODE" CHAR(6), 
	"BRD_PURPS_CODE" CHAR(10), 
	"EXAMIN_DE" DATE, 
	"REGIST_SE_CODE" CHAR(6), 
	"MOTHER_PIG_CO" NUMBER, 
	"PORKER_CO" NUMBER, 
	"MXMM_BRD_CO" NUMBER, 
	"RE_PREARNGE_DE" DATE, 
	"SEAR_SE" CHAR(1), 
	"KEEP_CODE" CHAR(6), 
	"AVG_CNT" NUMBER, 
	 CONSTRAINT "TN_BLVSTCK_PK" PRIMARY KEY ("FRMHS_NO", "LSTKSP_CL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 45088768 NEXT 45088768 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KAHIS_DPL_IX"  ENABLE, 
	 CONSTRAINT "TN_BLVSTCK_R1" FOREIGN KEY ("LSTKSP_CL")
	  REFERENCES "DPL"."TC_LSTKSP" ("LSTKSP_CL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 35651584 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KAHIS_DPL_DT" ;

CREATE INDEX "DPL"."TN_BLVSTCK_IX_2" ON "DPL"."TN_BLVSTCK" ("LSTKSP_CL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 26214400 NEXT 26214400 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KAHIS_DPL_IX" ;

CREATE INDEX "DPL"."TN_BLVSTCK_FK_2" ON "DPL"."TN_BLVSTCK" ("FRMHS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 29360128 NEXT 29360128 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KAHIS_DPL_IX" ;

CREATE INDEX "DPL"."TN_BLVSTCK_IX_1" ON "DPL"."TN_BLVSTCK" ("REPRSNT_SN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOLOGGING 
  STORAGE(INITIAL 20971520 NEXT 20971520 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KAHIS_DPL_IX" ;

CREATE INDEX "DPL"."TN_BLVSTCK_IX_3" ON "DPL"."TN_BLVSTCK" (SUBSTR("LSTKSP_CL",1,4)||'00') 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KAHIS_DPL_DT" ;

GRANT DELETE ON "DPL"."TN_BLVSTCK" TO "LSFARM_EAI";
  GRANT UPDATE ON "DPL"."TN_BLVSTCK" TO "LSFARM_EAI";
  GRANT SELECT ON "DPL"."TN_BLVSTCK" TO "LSFARM_EAI";
  GRANT INSERT ON "DPL"."TN_BLVSTCK" TO "LSFARM_EAI";
  GRANT SELECT ON "DPL"."TN_BLVSTCK" TO "FIN";
  GRANT SELECT ON "DPL"."TN_BLVSTCK" TO "SPIDER";
  GRANT UPDATE ON "DPL"."TN_BLVSTCK" TO "EUS";
  GRANT SELECT ON "DPL"."TN_BLVSTCK" TO "EUS";
  GRANT INSERT ON "DPL"."TN_BLVSTCK" TO "EUS";
  GRANT DELETE ON "DPL"."TN_BLVSTCK" TO "EUS";
  GRANT UPDATE ON "DPL"."TN_BLVSTCK" TO "SIMUL";
  GRANT SELECT ON "DPL"."TN_BLVSTCK" TO "SIMUL";
  GRANT INSERT ON "DPL"."TN_BLVSTCK" TO "SIMUL";
  GRANT DELETE ON "DPL"."TN_BLVSTCK" TO "SIMUL";
  GRANT SELECT ON "DPL"."TN_BLVSTCK" TO "BQS";

COMMENT ON TABLE DPL.TN_BLVSTCK IS '농가사육가축';
COMMENT ON COLUMN DPL.TN_BLVSTCK.FRMHS_NO IS '농가번호';
COMMENT ON COLUMN DPL.TN_BLVSTCK.LSTKSP_CL IS '축종분류';
COMMENT ON COLUMN DPL.TN_BLVSTCK.BRD_HAD_CO IS '사육두수';
COMMENT ON COLUMN DPL.TN_BLVSTCK.REPRSNT_SN IS '대표순번';
COMMENT ON COLUMN DPL.TN_BLVSTCK.FRST_CRTR_ID IS '최초생성자ID';
COMMENT ON COLUMN DPL.TN_BLVSTCK.FRST_CREAT_DT IS '최초생성일시';
COMMENT ON COLUMN DPL.TN_BLVSTCK.FRST_CRTR_IP_NM IS '최초생성자IP명';
COMMENT ON COLUMN DPL.TN_BLVSTCK.LAST_CHANGER_ID IS '최종변경자ID';
COMMENT ON COLUMN DPL.TN_BLVSTCK.LAST_CHANGE_DT IS '최종변경일시';
COMMENT ON COLUMN DPL.TN_BLVSTCK.LAST_CHANGER_IP_NM IS '최종변경자IP명';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MASTER_ORG IS '관리기관';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MASTER_STTUS_SE IS '축종운영상태';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MASTER_ORG_TEMP IS '관리기관임시';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MASTER_ORG_TEMP2 IS '관리기관임시2';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MASTER_ORG_ORI IS '관리기관원본';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MGR_CODE IS '운영상태';
COMMENT ON COLUMN DPL.TN_BLVSTCK.FRMHS_LSTKSP_CL_CODE IS '방역본부축종코드';
COMMENT ON COLUMN DPL.TN_BLVSTCK.BRD_PURPS_CODE IS '사육목적코드';
COMMENT ON COLUMN DPL.TN_BLVSTCK.EXAMIN_DE IS '조사일자';
COMMENT ON COLUMN DPL.TN_BLVSTCK.REGIST_SE_CODE IS '등록구분코드(409)_조사구분코드';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MOTHER_PIG_CO IS '모돈수';
COMMENT ON COLUMN DPL.TN_BLVSTCK.PORKER_CO IS '비육돈수';
COMMENT ON COLUMN DPL.TN_BLVSTCK.MXMM_BRD_CO IS '최대사육두수';
COMMENT ON COLUMN DPL.TN_BLVSTCK.RE_PREARNGE_DE IS '재입식예정일자';
COMMENT ON COLUMN DPL.TN_BLVSTCK.SEAR_SE IS '조회구분(Y/N)';
COMMENT ON COLUMN DPL.TN_BLVSTCK.KEEP_CODE IS '사육방식';
COMMENT ON COLUMN DPL.TN_BLVSTCK.AVG_CNT IS '평균사육두수';