-- ============================================================
-- M2MSYS PDB의 m2msys 계정으로 실행
-- 실행 예:
--   docker exec -i kahis-batch-monitor-oracle sqlplus -s m2msys/m2msys@//localhost:1521/M2MSYS @/scripts/oracle-m2msys-schema.sql
-- ============================================================

WHENEVER SQLERROR CONTINUE
SET ECHO ON

-- 멱등 실행
DROP TABLE TN_MOBILE_FRMHS_INFO CASCADE CONSTRAINTS;
DROP TABLE TN_MOBILE_BLVSTCK_HIST CASCADE CONSTRAINTS;
-- 옛 토폴로지 잔존 객체 정리
DROP TABLE TN_BLVSTCK CASCADE CONSTRAINTS;
DROP TABLE VIEW_FRMHS CASCADE CONSTRAINTS;
DROP TABLE TN_FRMHS CASCADE CONSTRAINTS;
DROP TABLE TN_FARMHS_NO_MAPNG CASCADE CONSTRAINTS;
DROP DATABASE LINK M2MSYS;
DROP DATABASE LINK DL_LSFARM;

WHENEVER SQLERROR EXIT SQL.SQLCODE

-- ============================================================
-- 테이블
-- ============================================================
-- 매퍼 selectFarmIdDpl의 @M2MSYS DB Link로 접근
CREATE TABLE TN_MOBILE_FRMHS_INFO (
  FDB_FRMHS_SN     NUMBER NOT NULL,
  FRMHS_NO         VARCHAR2(20) NOT NULL
);

-- 매퍼 selectMobileBreedingLivestockHistory의 @M2MSYS DB Link로 접근
CREATE TABLE TN_MOBILE_BLVSTCK_HIST (
  FRMHS_NO         VARCHAR2(20) NOT NULL,
  LSTKSP_CL        VARCHAR2(10) NOT NULL,
  BRD_HAD_CO       NUMBER,
  LAST_CHANGE_DT   DATE
);

-- ============================================================
-- 시드 (REQUIREMENTS 3.4 사례 기반)
-- 케이스 A (LIKELY_NORMAL): 가금류 농가 20418398
-- 케이스 B (LIKELY_ANOMALY): 한우 농가 00129932
-- 케이스 C (UNKNOWN): 신규 농가 99999999
-- ============================================================
INSERT INTO TN_MOBILE_FRMHS_INFO VALUES (1001, '20418398');
INSERT INTO TN_MOBILE_FRMHS_INFO VALUES (1002, '00129932');
INSERT INTO TN_MOBILE_FRMHS_INFO VALUES (1099, '99999999');

-- 케이스 A: HIST에 ×0.5~×2.0 매칭값 존재
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('20418398', '415002', 3500, SYSDATE - 7);
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('20418398', '415002', 3000, SYSDATE - 30);
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('20418398', '415002', 4000, SYSDATE - 90);
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('20418398', '415002', 30,   SYSDATE - 200);

-- 케이스 B: HIST 100미만, current 9222와 매칭 없음
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('00129932', '412002', 92, SYSDATE - 5);
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('00129932', '412002', 90, SYSDATE - 30);
INSERT INTO TN_MOBILE_BLVSTCK_HIST VALUES ('00129932', '412002', 88, SYSDATE - 90);

-- 케이스 C: HIST 비어 있음 (UNKNOWN)

COMMIT;

PROMPT === M2MSYS row counts ===
SELECT 'TN_MOBILE_FRMHS_INFO' AS T, COUNT(*) AS C FROM TN_MOBILE_FRMHS_INFO
UNION ALL SELECT 'TN_MOBILE_BLVSTCK_HIST', COUNT(*) FROM TN_MOBILE_BLVSTCK_HIST;

EXIT
